### ISSUE TITLE
Consider removing expvars

### ISSUE THREAD

**Issue by rmarianski** [tilezen/tapalcatl#21]
We went back and forth on expvars, and I don't think we'll end up using it any longer. @zerebubuth can we remove it from the code base?

**Comment by zerebubuth** [comment]
Yes, nothing is relying on it.

I think it could be quite useful, though, if we need to poke at a running server to see what the variable values are. If I remember right, the vars exposed over HTTP are fairly comprehensive and also include a bunch of stuff about GC behaviour.

If we're confident we won't ever need that stuff, then let's go ahead and pull the expvars out.

**Comment by rmarianski** [comment]
Do you think we should be logging that periodically on a background thread? And also pushing that into graphite so it shows up in grafana?

I think it would be great if we got ourselves to a place where we never felt the need to ssh into an instance, but that might be a pipe dream :)

**Comment by zerebubuth** [comment]
Yes, pushing it into graphite sounds like a good idea. I'm sure we can get access to that information relatively easily from our metrics pusher.

Not `ssh`ing into an instance will have to be a reality at some point! If we move to containers it's going to be somewhat painful to find out which host the container is in, `ssh` to that, then whatever `docker` stuff is needed to fake a login shell.
