### ISSUE TITLE
Better healthcheck check

### ISSUE THREAD

**Issue by zerebubuth** [tilezen/tapalcatl#23]
Thanks to @iandees for pointing this out yesterday.

At the moment, the healthcheck just checks that the service is up. Unfortunately, this means that when the service is working fine, but [S3 isn't](https://news.ycombinator.com/item?id=13755673), the service reports an OK healthcheck while returning 5xx errors to all requests.

We could solve this in several ways, and a couple that we briefly discussed were:

1. Check a static file on S3 when healthcheck is called. This would mean we'd need to remember to put the static file in place, but assuming it's one per bucket then that would be a infrequent. Alternatively, we could use a different API operation, such as `LIST` or [`HEAD bucket`](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html) which doesn't require a static file.
2. Passively check the rate of 5xx errors coming from S3 over the past minute(s) and if >80% of requests resulted in a 5xx, then fail the healthcheck. This seems like a good metric for failure, but passive monitoring means it'll never _come back_ afterwards (unless we treat 0/0 as success, in which case it might ping-pong up and down when it should stay failed).

I was thinking about the second last night, but now it looks like a bad idea. What do you think, @iandees & @rmarianski?

**Comment by rmarianski** [comment]
I like health checks to be very simple, and would prefer the first one. And within that, would prefer to request an object instead of listing the bucket, because that's what the service does. We could just make a file at the root of the bucket like you mentioned, eg `/_healthcheck` and have all services that depend on s3 check that.

**Comment by nvkelso** [comment]
I also prefer the single file. I'm fine with new health check file, or we could check that the tilejson exists (which has gone missing in the past).

**Comment by iandees** [comment]
Yep, I agree that we should check for a tile. I'd say the 0/0/0 tile rather than a file we have to remember to add.

Are there other services that tapalcatl uses that we should also check in tapalcatl's healthcheck?

**Comment by rmarianski** [comment]
> I'd say the 0/0/0 tile rather than a file we have to remember to add.

I still prefer the synthetic file. We'd only have to add the synthetic file once, and never again for subsequent deployments. Checking 0/0/0 would mean that we would be unable to go live with a new date prefix unless we were sure that 0/0/0 was generated first.

> Are there other services that tapalcatl uses that we should also check in tapalcatl's healthcheck?

Don't think so. We send metrics over udp, but that shouldn't be involved with the health check.

**Comment by nvkelso** [comment]
Would the synthetic health check file need to be added per deploy into each new date prefixed bucket?

**Comment by rmarianski** [comment]
> Would the synthetic health check file need to be added per deploy into each new date prefixed bucket?

No. See https://github.com/tilezen/tapalcatl/issues/23#issuecomment-283381465

**Comment by nvkelso** [comment]
Because the health check would talk directly to S3 and not to the
tile.mapzen.com endpoint?

**Comment by rmarianski** [comment]
> Because the health check would talk directly to S3

Yes, exactly.
